### ISSUE TITLE
Sorting causes future dom-repeat items to be added in wrong order

### ISSUE THREAD

**Issue by Lange** [sharedlabs/sortable-list#1]
Hi there!

I'd first like to say that this element is great. It's by far the simplest implementation of this functionality that I've seen, and for the most part works nicely! I've been wanting exactly this element for quite some time.

The issue I've encountered is when using a `dom-repeat` template inside of a `sortable-list`. When `dom-repeat` instantiates a new child, it uses `insertBefore` to insert that child before the `dom-repeat` template in the DOM. The exact line in question is [dom-repeat.html#L702](https://github.com/Polymer/polymer/blob/master/src/lib/template/dom-repeat.html#L702).

![image](https://cloud.githubusercontent.com/assets/873012/21285009/2174fb84-c3f2-11e6-945f-2300b61e12dc.png)

However, when `sortable-list` calls `_finishTrackEnd`, it re-appends all the items to the end of the parent node, thereby placing them all _after_ the `dom-repeat`. This means that whenever a new item is added to the `dom-repeat`, it will actually appear _before_ all the previously sorted items, instead of after.

![image](https://cloud.githubusercontent.com/assets/873012/21285011/30e10cd4-c3f2-11e6-9d08-6185ed49b3be.png)
![image](https://cloud.githubusercontent.com/assets/873012/21285012/3b8d06ba-c3f2-11e6-903f-38a6d94247e9.png)

I've created a minimial jsfiddle to demonstrate this. The jsfiddle has instructions on how to replicate this issue: https://jsfiddle.net/e37uvu0a/1/

EDIT: I've also recorded a GIF that more clearly demonstrates the problem:
![2016-12-17_11-06-58](https://cloud.githubusercontent.com/assets/873012/21288456/00c90162-c449-11e6-9b39-080cb500738e.gif)

Thanks,
Alex

**Comment by pdgago** [comment]
@Lange Hi!! sorry for not replying before, I just read it.

Thanks a lot for such a detailed report. It should be fixed now!
