### ISSUE TITLE
Demo does not work

### ISSUE THREAD

**Issue by Arosner** [sharedlabs/sortable-list#7]
When I viewed the demo in Safari nothing rendered within the demo page aside from the header "Drag the Items". In chrome I can see the animal images but am unable to drag them.

**Comment by FynjyAC** [comment]
Hi. I have no problems with the demo in chrome [https://sharedlabs.github.io/sortable-list/components/sortable-list/index.html](url). Images of animals are dragged without problems

**Comment by mukuls-brdsys** [comment]
Replace `dragHandle: String` with
` dragHandle: {
        type: String,
        value: ""
  },
`

**Comment by pdgago** [comment]
thanks, it's fixed now
